### ISSUE TITLE
[BUG] Extension Fails to Find Mod Directory in 2.2.42

### ISSUE THREAD

**Issue by dedfishe** [ghostboats/bg3_mod_helper#65]
## Issue Summary
Extension throws "Mods directory does not exist" error upon loading despite providing a valid path in user settings.

## Issue Details
The extension only throws this error in **2.2.42**. The extension works fine if I revert to **2.2.3**. I have tried providing the path with forward slashes instead to no avail.

### Console Dump
[log.txt](https://github.com/user-attachments/files/15743226/log.txt)
### User Settings
(No difference between start and after loading extension)
```json
{
    "git.autofetch": true,
    "git.confirmSync": false,
    "terminal.integrated.enableMultiLinePasteWarning": "auto",
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "workbench.colorTheme": "One Dark Pro",
    "workbench.startupEditor": "none",
    "github.copilot.enable": {
        "*": true,
        "plaintext": false,
        "markdown": false,
        "scminput": false
    },
    "git.openRepositoryInParentFolders": "always",
    "editor.fontFamily": "'Monaspace Neon', Consolas, 'Courier New', monospace",
    "editor.fontLigatures": true,
    "vim.useCtrlKeys": false,
    "terminal.integrated.automationProfile.windows": null,
    "bg3ModHelper.gameInstallLocation": "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Baldurs Gate 3",
    "bg3ModHelper.lslibPath": "E:\\BG3 Modding\\ExportTool-v1.19.5\\Packed",
    "bg3ModHelper.modDestPath": "C:\\Users\\daria\\AppData\\Local\\Larian Studios\\Baldur's Gate 3\\Mods",
    "bg3ModHelper.hover.showPath": false
}
```
### Workspace Settings
(No difference between start and after loading extension)
```json
{
    "bg3ModHelper.rootModPath": "e:\\BG3 Modding\\MyMods\\Test"
}
```

**Comment by ghostboats** [comment]
Thanks for the report and all the details! I will be taking a look into this later today/tomorrow morning to keep you in the loop👍

**Comment by khbsd** [comment]
is there a mod directory structure set up in this folder yet? ie, `Generated, Public, Localization` etc

EDIT: 
if you have, can you send the output from the Extension Host?

**Comment by ghostboats** [comment]
Also, something to note, do you have multiple vscode windows open or just the one?

**Comment by serevael** [comment]
It seems that the issue was caused by me not having the directory structure set up for the given mod. Is this intentional? I can't imagine that I'm the only user that would want to start a mod project fresh from an empty directory.

Sorry for the possibly false bug report. I read the docs a few times over and I can't find anywhere where it says this is a requirement. Additionally, the error message is ambiguous and I interpreted it to mean there was a problem with my configured mod destination path.

**Comment by robogena** [comment]
I'm having this same exact issue after updating to 2.2.42. The error happens now when I 'Open Folder...' on any mod folder for the first time, regardless of directory structure. I have to close the folder and reopen it for the extension to work. The only thing I can think of is that the settings.json isn't created for the mod folder until that moment and now maybe the extension isn't immediately recognizing it?

My settings.json looks fine(?) and the extension otherwise works as intended, but only after that reload.
`"bg3ModHelper.rootModPath": "c:\\Program Files (x22)\\BG3 Modders Multitool\\UnpackedMods\\test"`

FWIW, I usually have multiple vscode windows open but I haven't seen it affect the error at all.

ETA: Did some more testing. I get the 'Mods directory does not exist' error when opening _any_ folder for the first time in a new window, even if there's already a settings.json for the rootModPath already in there. Extension still needs the close and reopen to work. For now I've rolled back to 2.2.3.

**Comment by ghostboats** [comment]
Hey all, work has been a bit busier on me this month than usual so sadly haven't had as much time to work on this. We do have a release in the works that should (hopefully) address the issues here coming out soonish, possibly near the end of this week.

**Comment by robogena** [comment]
No problem! And no rush, real life comes first! Thank you guys for all the work you've put into this already!

**Comment by ghostboats** [comment]
I believe this has been resolved for a bit? Sorry if not so, i think you can still comment even on closed so please do if its not. Sorry its been a minute.
