### ISSUE TITLE
[BUG?] Handle Insertion Prompt

### ISSUE THREAD

**Issue by durstjd** [ghostboats/bg3_mod_helper#68]
Handle insertion via Ctrl+Shift+H no longer prompts for handle content starting in 2.2.59. I believe this is the intended functionality of bg-mod-helper.insertHandleDisposable. In 2.2.57, Ctrl+Shift+H calls bg3-mod-helper.insertHandle.

This is not a big deal for me as I have adjusted the keybind to insertHandle for my own productivity, but I was curious if this is intentional and if the custom keybind may be overwritten after future updates.

Thanks

**Comment by ghostboats** [comment]
Sorry it took so long to get back to you. I swapped both commands so it should be fine now. Sending the update in a few, have some other things to push quick as well. honestly im not sure how it was changed before. Now control shift h will prompt for you to enter text for the newly generate handle. You may need to swap it around due to your custom bindings but not sure. Would recommend reaching out on the discord for quicker responses back, sorry again! (https://discord.com/channels/1211056047784198186/1233823019621941268)
